[pytest]
asyncio_mode = auto
testpaths = tests
log_cli = true
log_cli_level = WARNING
python_classes = Test[A-Z]*[a-z]
filterwarnings =
    ignore::pytest.PytestCollectionWarning
addopts =
    -v
    --tb=short
    --html=reports/pytest_report.html
    --self-contained-html
